name: Init SQL

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker compose install
      uses: hoverkraft-tech/compose-action@v2.2.0
      with: 
        compose-file: "./docker-compose.yml"







    # - name: Setup PostgreSQL
    #   uses: tj-actions/install-postgresql@v3
    #   with:
    #     postgresql-version: 17

